# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsin',
            name='bank_acc',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='payment_fees',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='time',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='total_fees',
        ),
        migrations.RemoveField(
            model_name='accountsin',
            name='username',
        ),
    ]
